/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netmap.panels;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import netmap.components.ScreenPortTableModel;
import netmap.database.managers.PortManager;
import netmap.entities.Equipment;
import netmap.entities.Port;
import netmap.entities.ScreenEquipment;
import netmap.entities.ScreenPort;
import netmap.util.Application;

/**
 *
 * @author Julia
 */
public class ScreenEquipmentPanel extends javax.swing.JDialog
{
    private ScreenEquipment screenEquipment;
    private Equipment equipment;
    private int code = JOptionPane.CANCEL_OPTION;

    public ScreenEquipmentPanel(ScreenEquipment screenEquipment)
    {
        this.screenEquipment = screenEquipment;
     
        init();
        
        lbTitle.setText(screenEquipment.getName());
        tfName.setText(screenEquipment.getName());
        loadScreenEquipmentPorts();
    }
    
    public ScreenEquipmentPanel(Equipment e)
    {
        this.equipment = e;
        
        init();
        
        lbTitle.setText("Novo "+e.getDescription());
        loadScreenEquipmentPorts();
    }
    
    private void init()
    {
        initComponents();
        
        tablePorts.putClientProperty("terminateEditOnFocusLost", true);
    }
    
    public ScreenEquipment getScreenEquipment()
    {
        if (screenEquipment == null)
        {
            screenEquipment = new ScreenEquipment();
        }
        
        screenEquipment.setName(tfName.getText());
        screenEquipment.setMapId(1);
        screenEquipment.setEquipmentId(equipment.getId());
        
        return screenEquipment;
    }

    public int getCode()
    {
        return code;
    }
    
    public List<ScreenPort> getScreenPorts()
    {
        return ((ScreenPortTableModel)tablePorts.getModel()).getPorts();
    }
    
    private void loadScreenEquipmentPorts()
    {
        List<ScreenPort> ports;
        
        if (screenEquipment == null)
        {
            ports = new ArrayList<>();
            for (Port p : PortManager.getInstance().get(equipment))
            {
                ScreenPort screenPort = new ScreenPort();
                screenPort.setType(p.getType());
                
                ports.add(screenPort);
            }
        }
        else
        {
            ports = new ArrayList<>();
        }
        
        tablePorts.setModel(new ScreenPortTableModel(ports));
        
        JComboBox combo = new JComboBox<>();
        combo.setModel(new DefaultComboBoxModel<>(ScreenPort.SWITCHPORTS.values()));
        tablePorts.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(combo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        lbTitle = new javax.swing.JLabel();
        pnData = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        panelPorts = new javax.swing.JPanel();
        scrollPorts = new javax.swing.JScrollPane();
        tablePorts = new javax.swing.JTable();
        pnButtons = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTitle.setText("Novo Equipamento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(lbTitle, gridBagConstraints);

        pnData.setLayout(new java.awt.GridBagLayout());

        lbName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbName.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnData.add(lbName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnData.add(tfName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 15);
        add(pnData, gridBagConstraints);

        panelPorts.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Portas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        panelPorts.setLayout(new java.awt.GridBagLayout());

        tablePorts.setModel(new ScreenPortTableModel());
        scrollPorts.setViewportView(tablePorts);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        panelPorts.add(scrollPorts, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 15);
        add(panelPorts, gridBagConstraints);

        pnButtons.setLayout(new java.awt.GridBagLayout());

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btOkActionPerformed(evt);
            }
        });
        pnButtons.add(btOk, new java.awt.GridBagConstraints());

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnButtons.add(btCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 15, 15);
        add(pnButtons, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btOkActionPerformed
    {//GEN-HEADEREND:event_btOkActionPerformed
        if (tfName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(Application.getInstance().getMainFrame(), "O nome do equipamento é obrigatório");
            tfName.grabFocus();
        }
        else
        {
            code = JOptionPane.OK_OPTION;
            this.dispose();
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCancelActionPerformed
    {//GEN-HEADEREND:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel panelPorts;
    private javax.swing.JPanel pnButtons;
    private javax.swing.JPanel pnData;
    private javax.swing.JScrollPane scrollPorts;
    private javax.swing.JTable tablePorts;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
