/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netmap.frames;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import netmap.util.Application;

/**
 *
 * @author Julia
 */
public class AboutFrame extends javax.swing.JDialog
{

    /**
     * Creates new form AboutFrame
     */
    public AboutFrame()
    {
        initComponents();
        
        JTable tableAbout = new JTable();
        tableAbout.setSelectionBackground(tableAbout.getBackground());
        tableAbout.setSelectionForeground(tableAbout.getForeground());
        tableAbout.setShowGrid(false);
        
        final String[] rows = {
            "Versão "+Application.MAJOR_VERSION+"."+Application.MINOR_VERSION+" beta",
            "Desenvolvido por Darlan Rodrigo Ullmann",
            "",
            "",
            "Bibliotecas:",
            "Image scaling por Riyad Kalla",
            "    https://github.com/rkalla/imgscalr",
            "Ícones projetados por Madebyoliver do Flaticon",
            "    http://www.flaticon.com"
        };
        
        tableAbout.setModel(new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex)
            {
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }

            @Override
            public int getColumnCount()
            {
                return 1;
            }

            @Override
            public int getRowCount()
            {
                return rows.length;
            }

            @Override
            public Object getValueAt(int row, int column)
            {
                return rows[row];
            }
        });
        
        panelAbout.add(tableAbout, new GridBagConstraints(0, 0, 1, 1, 1.0, 1.0, 
                GridBagConstraints.EAST, GridBagConstraints.BOTH, 
                new Insets(5, 5, 5, 5), 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAbout = new javax.swing.JPanel();
        btClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Network Mapper");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelAbout.setBorder(javax.swing.BorderFactory.createTitledBorder("Sobre"));
        panelAbout.setPreferredSize(new java.awt.Dimension(360, 260));
        panelAbout.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(panelAbout, gridBagConstraints);

        btClose.setText("Fechar");
        btClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 15, 15);
        getContentPane().add(btClose, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCloseActionPerformed
    {//GEN-HEADEREND:event_btCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JPanel panelAbout;
    // End of variables declaration//GEN-END:variables
}
