/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netmap.frames;

/**
 *
 * @author Julia
 */
public class ErrorFrame extends javax.swing.JDialog
{

    public ErrorFrame(Exception e)
    {
        this(null, e);
    }

    /**
     * Creates new form ErrorFrame
     * @param title
     * @param e
     */
    public ErrorFrame(String title, Exception e)
    {
        initComponents();
        
        if (title != null)
        {
            lbError.setText(title);
        }
        setException(e);
    }

    public void setException(Exception exception)
    {
        for (StackTraceElement trace : exception.getStackTrace())
        {
            taStack.append(trace.toString()+"\n");
        }
        taStack.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        lbImage = new javax.swing.JLabel();
        lbError = new javax.swing.JLabel();
        spStack = new javax.swing.JScrollPane();
        taStack = new javax.swing.JTextArea();
        btClose = new javax.swing.JButton();

        setTitle("Erro!");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 10, 0);
        getContentPane().add(lbImage, gridBagConstraints);

        lbError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbError.setText("Erro!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 15);
        getContentPane().add(lbError, gridBagConstraints);

        taStack.setEditable(false);
        taStack.setColumns(20);
        taStack.setRows(5);
        taStack.setMinimumSize(new java.awt.Dimension(164, 94));
        spStack.setViewportView(taStack);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 15);
        getContentPane().add(spStack, gridBagConstraints);

        btClose.setText("Fechar");
        btClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 15, 15);
        getContentPane().add(btClose, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCloseActionPerformed
    {//GEN-HEADEREND:event_btCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbImage;
    private javax.swing.JScrollPane spStack;
    private javax.swing.JTextArea taStack;
    // End of variables declaration//GEN-END:variables
}
