/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netmap.frames;

import netmap.panels.BrandsPanel;
import netmap.panels.EquipmentsPanel;
import netmap.panels.MapPanel;
import java.awt.CardLayout;
import netmap.panels.EquipmentTypesPanel;

/**
 *
 * @author darlan.ullmann
 */
public class MainFrame extends javax.swing.JFrame
{
    private final String MAPCARD = "MAP_CARD";
    private final String BRANDCARD = "BRAND_CARD";
    private final String EQUIPMENTTYPECARD = "EQUIPMENTTYPE_CARD";
    private final String EQUIPMENTCARD = "EQUIPMENT_CARD";
    
    private final MapPanel mapPanel;
    private final BrandsPanel brandsPanel;
    private final EquipmentTypesPanel equipmentTypesPanel;
    private final EquipmentsPanel equipmentsPanel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
        
        mapPanel = new MapPanel();
        brandsPanel = new BrandsPanel();
        equipmentTypesPanel = new EquipmentTypesPanel();
        equipmentsPanel = new EquipmentsPanel();
        
        panelCards.add(mapPanel, MAPCARD);
        panelCards.add(brandsPanel, BRANDCARD);
        panelCards.add(equipmentTypesPanel, EQUIPMENTTYPECARD);
        panelCards.add(equipmentsPanel, EQUIPMENTCARD);
        
        btBackToMap.setVisible(false);
        
        loadMap();
    }
    
    private void loadMap()
    {
        mapPanel.load();
        
        ((CardLayout)panelCards.getLayout()).show(panelCards, MAPCARD);
        lbTitle.setText("Mapa");
        btBackToMap.setVisible(false);
        btEdit.setVisible(true);
        
        miMap.setEnabled(false);
        miBrands.setEnabled(true);
        miEquipmentTypes.setEnabled(true);
        miEquipments.setEnabled(true);
    }
    
    private void loadBrands()
    {
        brandsPanel.loadBrands();
        
        ((CardLayout)panelCards.getLayout()).show(panelCards, BRANDCARD);
        lbTitle.setText("Marcas");
        btBackToMap.setVisible(true);
        btEdit.setVisible(false);
        
        miMap.setEnabled(true);
        miBrands.setEnabled(false);
        miEquipmentTypes.setEnabled(true);
        miEquipments.setEnabled(true);
    }
    
    private void loadEquipmentTypes()
    {
        equipmentTypesPanel.loadEquipmentTypes();
        
        ((CardLayout)panelCards.getLayout()).show(panelCards, EQUIPMENTTYPECARD);
        lbTitle.setText("Tipos de Equipamentos");
        btBackToMap.setVisible(true);
        btEdit.setVisible(false);
        
        miMap.setEnabled(true);
        miBrands.setEnabled(true);
        miEquipmentTypes.setEnabled(false);
        miEquipments.setEnabled(true);
    }
    
    private void loadEquipments()
    {
        equipmentsPanel.load();
        
        ((CardLayout)panelCards.getLayout()).show(panelCards, EQUIPMENTCARD);
        lbTitle.setText("Equipamentos");
        btBackToMap.setVisible(true);
        btEdit.setVisible(false);
        
        miMap.setEnabled(true);
        miBrands.setEnabled(true);
        miEquipmentTypes.setEnabled(true);
        miEquipments.setEnabled(false);
    }
    
    public void shutdown()
    {
        mapPanel.saveProperties();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTitle = new javax.swing.JPanel();
        panelTitleComponents = new javax.swing.JPanel();
        btBackToMap = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        btEdit = new javax.swing.JButton();
        panelCards = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuModels = new javax.swing.JMenu();
        miMap = new javax.swing.JMenuItem();
        miBrands = new javax.swing.JMenuItem();
        miEquipmentTypes = new javax.swing.JMenuItem();
        miEquipments = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Network Mapper");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelTitle.setBackground(java.awt.SystemColor.activeCaption);
        panelTitle.setLayout(new java.awt.GridBagLayout());

        panelTitleComponents.setOpaque(false);
        panelTitleComponents.setLayout(new java.awt.GridBagLayout());

        btBackToMap.setText("<<< Voltar ao mapa");
        btBackToMap.setOpaque(false);
        btBackToMap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btBackToMapActionPerformed(evt);
            }
        });
        panelTitleComponents.add(btBackToMap, new java.awt.GridBagConstraints());

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTitle.setText("Mapa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        panelTitleComponents.add(lbTitle, gridBagConstraints);

        btEdit.setText("Editar");
        btEdit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btEditActionPerformed(evt);
            }
        });
        panelTitleComponents.add(btEdit, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelTitle.add(panelTitleComponents, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(panelTitle, gridBagConstraints);

        panelCards.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(panelCards, gridBagConstraints);

        menuModels.setText("Menu");

        miMap.setText("Mapa");
        miMap.setEnabled(false);
        miMap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miMapActionPerformed(evt);
            }
        });
        menuModels.add(miMap);

        miBrands.setText("Marcas");
        miBrands.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miBrandsActionPerformed(evt);
            }
        });
        menuModels.add(miBrands);

        miEquipmentTypes.setText("Tipos de Equipamentos");
        miEquipmentTypes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miEquipmentTypesActionPerformed(evt);
            }
        });
        menuModels.add(miEquipmentTypes);

        miEquipments.setText("Equipamentos");
        miEquipments.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miEquipmentsActionPerformed(evt);
            }
        });
        menuModels.add(miEquipments);

        menuBar.add(menuModels);

        menuAbout.setText("Sobre");

        miAbout.setText("Sobre");
        miAbout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                miAboutActionPerformed(evt);
            }
        });
        menuAbout.add(miAbout);

        menuBar.add(menuAbout);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miBrandsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miBrandsActionPerformed
    {//GEN-HEADEREND:event_miBrandsActionPerformed
        loadBrands();
    }//GEN-LAST:event_miBrandsActionPerformed

    private void btBackToMapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btBackToMapActionPerformed
    {//GEN-HEADEREND:event_btBackToMapActionPerformed
        loadMap();
    }//GEN-LAST:event_btBackToMapActionPerformed

    private void miMapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miMapActionPerformed
    {//GEN-HEADEREND:event_miMapActionPerformed
        loadMap();
    }//GEN-LAST:event_miMapActionPerformed

    private void miEquipmentsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miEquipmentsActionPerformed
    {//GEN-HEADEREND:event_miEquipmentsActionPerformed
       loadEquipments();
    }//GEN-LAST:event_miEquipmentsActionPerformed

    private void miEquipmentTypesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miEquipmentTypesActionPerformed
    {//GEN-HEADEREND:event_miEquipmentTypesActionPerformed
        loadEquipmentTypes();
    }//GEN-LAST:event_miEquipmentTypesActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miAboutActionPerformed
    {//GEN-HEADEREND:event_miAboutActionPerformed
        AboutFrame aboutFrame = new AboutFrame();
        aboutFrame.setLocationRelativeTo(this);
        aboutFrame.setModal(true);
        aboutFrame.setVisible(true);
    }//GEN-LAST:event_miAboutActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btEditActionPerformed
    {//GEN-HEADEREND:event_btEditActionPerformed
        if (mapPanel.getStatus() == MapPanel.STATUS_VIEW)
        {
            if (mapPanel.setStatus(MapPanel.STATUS_EDIT))
            {
                btEdit.setText("Salvar");
            }
        }
        else
        {
            if (mapPanel.setStatus(MapPanel.STATUS_VIEW))
            {
                btEdit.setText("Editar");
            }
        }
    }//GEN-LAST:event_btEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBackToMap;
    private javax.swing.JButton btEdit;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuModels;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miBrands;
    private javax.swing.JMenuItem miEquipmentTypes;
    private javax.swing.JMenuItem miEquipments;
    private javax.swing.JMenuItem miMap;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTitleComponents;
    // End of variables declaration//GEN-END:variables
}
